engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    checks:
      fatal:
        enabled: false
    config:
      config: .eslintrc
  fixme:
    enabled: true
ratings:
  paths:
  - src/**
exclude_paths:
- test/
- dest/
